### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by wwj718** [LivelyKernel/lively.next#1]
Hi,
I try to install lively.next.  I encountered the following error:

my development environment :

```
MacOS: 10.13.5
NodeJS: v10.15.0
NPM: 6.10.2
```

```
compiling flatn

Error: Command failed: npm run build
(node:85461) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/Users/wuwenjie/mylab/codelabclub/lively.next/lively.modules/dist/lively.modules.js:29200
}((this.lively.sourceTransform = this.lively.sourceTransform || {}),lively.lang,lively.classes,lively.ast,transformJSX));
                                                                                                          ^

ReferenceError: transformJSX is not defined
    at /Users/wuwenjie/mylab/codelabclub/lively.next/lively.modules/dist/lively.modules.js:29200:107
    at Object.<anonymous> (/Users/wuwenjie/mylab/codelabclub/lively.next/lively.modules/dist/lively.modules.js:29203:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/wuwenjie/mylab/codelabclub/lively.next/flatn/tools/build-cjs.js:5:45)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flatn@1.3.3 build: `node tools/build-cjs.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flatn@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuwenjie/.npm/_logs/2020-01-11T19_25_49_669Z-debug.log

> flatn@1.3.3 build /Users/wuwenjie/mylab/codelabclub/lively.next/flatn
> node tools/build-cjs.js


(node:85461) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/Users/wuwenjie/mylab/codelabclub/lively.next/lively.modules/dist/lively.modules.js:29200
}((this.lively.sourceTransform = this.lively.sourceTransform || {}),lively.lang,lively.classes,lively.ast,transformJSX));
                                                                                                          ^

ReferenceError: transformJSX is not defined
    at /Users/wuwenjie/mylab/codelabclub/lively.next/lively.modules/dist/lively.modules.js:29200:107
    at Object.<anonymous> (/Users/wuwenjie/mylab/codelabclub/lively.next/lively.modules/dist/lively.modules.js:29203:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/wuwenjie/mylab/codelabclub/lively.next/flatn/tools/build-cjs.js:5:45)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flatn@1.3.3 build: `node tools/build-cjs.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flatn@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuwenjie/.npm/_logs/2020-01-11T19_25_49_669Z-debug.log

compiling lively.serializer2
compiling lively.graphics
compiling lively.keyboard
compiling lively.morphic
compiling lively.2lively
compiling lively.user
Error occurred during installation: ReferenceError: resource is not defined
    at global.replicateObjectDB (file:///Users/wuwenjie/mylab/codelabclub/lively.next/lively.installer/install.js:199:54)
    at Module.install (file:///Users/wuwenjie/mylab/codelabclub/lively.next/lively.installer/install.js:103:31)
```

how to solve it， thanks！

**Comment by rohinibarla** [comment]
I am also getting, similar compilation error with 

```
Error: Command failed: npm run build
(node:21243) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by merryman** [comment]
Install is updated and these errors should no longer be present. Closing this now.
