### ISSUE TITLE
Project failing to load

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1263]
**Describe the bug**
I can't load the project engageLively--galyleo -dashboard.  lively.next hangs, and the console error is:
```
__rootModule___commonjs-entry-30669367.js:119466 Uncaught (in promise) TypeError: livelySystemEnv is not a function
    at Object.module (__rootModule___commonjs-entry-30669367.js:119466:22)
    at __rootModule___commonjs-entry-30669367.js:124223:33
(anonymous) @ __rootModule___commonjs-entry-30669367.js:119466
(anonymous) @ __rootModule___commonjs-entry-30669367.js:124223
Promise.then (async)
(anonymous) @ __rootModule___commonjs-entry-30669367.js:124216
_callee2$ @ __rootModule___commonjs-entry-30669367.js:123609
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
customInstantiate @ __rootModule___commonjs-entry-30669367.js:123581
_callee$ @ __rootModule___commonjs-entry-30669367.js:123660
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
instantiate @ __rootModule___commonjs-entry-30669367.js:123674
(anonymous) @ deps.js:5447
Promise.then (async)
translateAndInstantiate @ deps.js:5441
(anonymous) @ deps.js:5374
Promise.then (async)
runFetchPipeline @ deps.js:5371
(anonymous) @ deps.js:5254
Promise.then (async)
(anonymous) @ deps.js:5253
Promise.then (async)
instantiate$1 @ deps.js:5220
(anonymous) @ deps.js:2609
Promise.then (async)
instantiate @ deps.js:2607
(anonymous) @ deps.js:2708
Promise.then (async)
resolveInstantiateDep @ deps.js:2682
instantiateDeps @ deps.js:2776
addDeps @ deps.js:2833
deepInstantiateDeps @ deps.js:2847
(anonymous) @ deps.js:2540
Promise.then (async)
RegisterLoader.<computed> @ deps.js:2526
(anonymous) @ deps.js:2205
Promise.then (async)
Loader.import @ deps.js:2204
SystemJSLoader.import @ deps.js:5887
_callee2$ @ __rootModule___commonjs-entry-30669367.js:119581
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
(anonymous) @ __rootModule___commonjs-entry-30669367.js:119657
_callee7$ @ bootstrap-b97f5084.js:703
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
deps.js:2000 Uncaught (in promise) TypeError: livelySystemEnv is not a function
    at __rootModule___commonjs-entry-30669367.js:119466:22
    at __rootModule___commonjs-entry-30669367.js:116854:19
    at ModuleInterface.ModuleInterface_define_ (__rootModule___commonjs-entry-30669367.js:120624:13)
    at Window.value (__rootModule___commonjs-entry-30669367.js:120555:29)
    at registerExtension (helpers.js:162:113)
    at Object.execute (__rootModule___commonjs-entry-30669367.js:123311:7)
    at doEvaluateDeclarative (deps.js:3043:40)
    at ensureEvaluate (deps.js:2917:29)
    at deps.js:2542:16
LoaderError__Check_error_message_for_loader_stack @ deps.js:2000
(anonymous) @ deps.js:2210
Promise.then (async)
_callee7$ @ bootstrap-b97f5084.js:705
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
__rootModule___commonjs-entry-30669367.js:119466 Uncaught (in promise) TypeError: livelySystemEnv is not a function
    at Object.module (__rootModule___commonjs-entry-30669367.js:119466:22)
    at __rootModule___commonjs-entry-30669367.js:124223:33
(anonymous) @ __rootModule___commonjs-entry-30669367.js:119466
(anonymous) @ __rootModule___commonjs-entry-30669367.js:124223
Promise.then (async)
(anonymous) @ __rootModule___commonjs-entry-30669367.js:124216
_callee2$ @ __rootModule___commonjs-entry-30669367.js:123609
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
customInstantiate @ __rootModule___commonjs-entry-30669367.js:123581
_callee$ @ __rootModule___commonjs-entry-30669367.js:123660
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
instantiate @ __rootModule___commonjs-entry-30669367.js:123674
(anonymous) @ deps.js:5447
Promise.then (async)
translateAndInstantiate @ deps.js:5441
(anonymous) @ deps.js:5374
Promise.then (async)
runFetchPipeline @ deps.js:5371
(anonymous) @ deps.js:5254
Promise.then (async)
(anonymous) @ deps.js:5253
Promise.then (async)
instantiate$1 @ deps.js:5220
(anonymous) @ deps.js:2609
Promise.then (async)
instantiate @ deps.js:2607
(anonymous) @ deps.js:2586
Promise.then (async)
resolveInstantiate @ deps.js:2564
RegisterLoader.<computed> @ deps.js:2525
(anonymous) @ deps.js:2205
Promise.then (async)
Loader.import @ deps.js:2204
SystemJSLoader.import @ deps.js:5887
_callee6$ @ __rootModule___commonjs-entry-30669367.js:119944
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
ModuleInterface_load_ @ __rootModule___commonjs-entry-30669367.js:119961
_callee8$ @ __rootModule___commonjs-entry-30669367.js:120085
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
(anonymous) @ __rootModule___commonjs-entry-30669367.js:74
(anonymous) @ __rootModule___commonjs-entry-30669367.js:63
ModuleInterface_reload_ @ __rootModule___commonjs-entry-30669367.js:120096
loadLocalConfig @ world-loading.js:55
await in loadLocalConfig (async)
loadWorld @ world-loading.js:80
await in loadWorld (async)
_callee10$ @ bootstrap-b97f5084.js:1093
tryCatch @ deps.js:705
invoke @ deps.js:935
(anonymous) @ deps.js:760
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:45
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
Promise.then (async)
asyncGeneratorStep @ __rootModule___commonjs-entry-30669367.js:55
_next @ __rootModule___commonjs-entry-30669367.js:67
client-command.js:347 [lively.shell] received exit message for command 1081 but it isn't registered!'
```

**To Reproduce**
Pull the repo https://github.com/engageLively/galyleo-dashboard, and then attempt to load the galyleo-dashboard project

**Screenshots**

**Setup**

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
91b1c2d9745ce849fc4da1a3c0771cc2b395012a

**Comment by linusha** [comment]
@rickmcgeer are you sure that you have run `./install.sh` or `make artifacts` before loading the dashboard project **and** opened a new browser with lively afterwards? Do you have any local changes inside of your dashboard project?

I could manually clone the latest version of the dashboard and load that in the latest version lively just now. :thinking:
