### ISSUE TITLE
Can't save a world when a dashboard has a chart in it

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#147]
But when I pull the chart out of the world, the error seems to go away.  Here's the error message:
Error saving world: Error: Error snapshotting morph: Cannot recreate morph from snapshot!
TypeError: Illegal constructor
    at ClassHelper.restoreIfClassInstance (https://matt.engagelively.com/lively.serializer2/class-helper.js:152:56)
    at ClassPlugin.deserializeObject (https://matt.engagelively.com/lively.serializer2/plugins.js:99:39)
    at ObjectPool.plugin_deserializeObject (https://matt.engagelively.com/lively.serializer2/object-pool.js:337:34)
    at ObjectRef.recreateObjFromSnapshot (https://matt.engagelively.com/lively.serializer2/object-pool.js:559:29)
    at Function.fromSnapshot (https://matt.engagelively.com/lively.serializer2/object-pool.js:636:49)
    at ObjectPool.readSnapshot (https://matt.engagelively.com/lively.serializer2/object-pool.js:236:47)
    at ObjectPool.resolveFromSnapshotAndId (https://matt.engagelively.com/lively.serializer2/object-pool.js:252:20)
    at Window.deserialize (https://matt.engagelively.com/lively.serializer2/index.js:55:20)
    at step2 (https://matt.engagelively.com/lively.serializer2/index.js:67:42)
    at async Window.createMorphSnapshot (https://matt.engagelively.com/lively.morphic/serialization.js:179:30)

It seems to be the dashboard that's the problem.  But it doesn't do much....

**Comment by merryman** [comment]
Please give a link to the world, with the exact steps to reproduce this. I failed to achieve anything you described.

**Comment by merryman** [comment]
I am closing this now.
