### ISSUE TITLE
Frozen page not loading

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1506]
**Describe the bug**
I've compiled the Galyleo project; it opens just fine in the editor but fails to load.  The error message in the console is:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'http://127.0.0.1:9011/local_projects/engageLively--galyleo-dashboard/bin/studio-en/__rootModule___commonjs-entry-624da34f.js')
    at ContextualLoader.import (deps.js:2910:24)
    at ModuleNamespace.renderFrozenPart (__rootModule___commonjs-entry-624da34f.js:178175:71)
    at index.html:59:84
```
The line causing the error is:
```
 this.loader.loads[this.key].dynamicDeps.push(key);
```
and `this.loader.loads` is undefined.
`this.loader` is a `SystemJSLoader`

**To Reproduce**

1. pull https://github.com/engageLively/galyleo-dashboard
2. run tools/build.sh --lang en
3. In a browser, load /bin/studio-en/index.html

**Screenshots**

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
97874fc6b9ca2be74bda64de4c9a687d3e8d4f8f

**Comment by merryman** [comment]
Appears like this happened due to #1492.

**Comment by rickmcgeer** [comment]
So is my fix to revert to  0ca7a0?

**Comment by merryman** [comment]
Todays a holiday in Germany. We will push a fix tomorrow. You can certainly try reverting if that helps you.

**Comment by rickmcgeer** [comment]
That's fine, I'll look forward to the fix.  Thanks!
