### ISSUE TITLE
Scene Graph Issue

### ISSUE THREAD

**Issue by DZL000** [LivelyKernel/lively.next#1662]
**Describe the bug**
Scene Graph malfunction

**To Reproduce**
I done a clean install latest lively.next (git cloning the latest repo and run install.sh, then start.sh) and encounter the error whenever I select a morph.

```
TypeError: Cannot read properties of undefined (reading 'filter')

    at Object.eval [as without] (http://localhost:9011/livelyClassesRuntime.js:1622:22)
    at NewSceneGraphTree.SceneGraphTree_isNodeOutOfSync_ (http://localhost:9011/projects/scene-graph.cp-064f8422.js:1006:38)
    at http://localhost:9011/projects/scene-graph.cp-064f8422.js:1068:44
    at Object.prewalk (http://localhost:9011/projects/__rootModule___commonjs-entry-8989093a.js:10594:9)
    at NewSceneGraphTree.SceneGraphTree_refresh_ (http://localhost:9011/projects/scene-graph.cp-064f8422.js:1067:18)
    at NewSceneGraphTree.SceneGraphTree_selectMorphInTarget_ (http://localhost:9011/projects/scene-graph.cp-064f8422.js:887:18)
    at MorphPanelModel.MorphPanelModel_selectNode_ (http://localhost:9011/projects/scene-graph.cp-064f8422.js:1322:34)
    at callOrSetTarget (http://localhost:9011/projects/__rootModule___commonjs-entry-8989093a.js:18377:78)
    at AttributeConnection.AttributeConnection_update_ (http://localhost:9011/projects/__rootModule___commonjs-entry-8989093a.js:18384:90)
    at LivelyWorld.connectionWrapper [as showHaloFor] (http://localhost:9011/projects/__rootModule___commonjs-entry-8989093a.js:18520:26)
```

**Screenshots**
<img width="1373" alt="Screenshot 2024-07-31 at 12 37 38" src="https://github.com/user-attachments/assets/e538f158-bac6-40c0-92e0-993f33ed40f0">

**Setup**
- macOS 14.5
- Arc 1.53
- node v20.11.0
- npm 10.2.4

**Version**: 
aba310a725ac03e36ff3e6a9ecd7648fdc2470c1

**Comment by linusha** [comment]
Hi @DZL000! Thanks for reporting this! We know of this issue and ware working on a fix. This is unfortunately related to 
#1654 and we still need some time to tackle the issue.

For now however, you should be able to use a workaround by switching to "slow load" mode. For that, just append "&fastLoad=false" the the URL of your project/world or use the button in the bottom right corner of the dashboard to switch. For slow load to be active, it should show the turtle before opening a project/world.

**Comment by DZL000** [comment]
The "slow load" workaround indeed works, thank you so much for your prompt reply!
