### ISSUE TITLE
ObjectEditor can't create new class

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#20]
fast load is off.  Here is the screen shot:
![Screen Shot 2020-10-17 at 08 45 28](https://user-images.githubusercontent.com/656259/96347256-491f8880-1055-11eb-9d2b-df48ae321f15.png)

**Comment by rickmcgeer** [comment]
Error message is: 
Error in interactive command open object editor: TypeError: Cannot read property 'constructor' of undefined
TypeError: Cannot read property 'constructor' of undefined
    at Window.Xn [as getClassName] (http://localhost:9011/worlds/__root_module__-c4d7431e.js:245:101)
    at ObjectEditorContext_selectClass_.selectedClassName.withContextDo.className.className (http://localhost:9011/lively.ide/js/objecteditor/context.js:382:40)
    at ObjectEditorContext.withContextDo (http://localhost:9011/lively.ide/js/objecteditor/context.js:296:30)
    at ObjectEditorContext.selectClass (http://localhost:9011/lively.ide/js/objecteditor/context.js:378:51)
    at ObjectEditorContext.selectLocalTarget (http://localhost:9011/lively.ide/js/objecteditor/context.js:198:26)
    at async ObjectEditorContext.selectTarget (http://localhost:9011/lively.ide/js/objecteditor/context.js:155:15)
    at async Function.for (http://localhost:9011/lively.ide/js/objecteditor/context.js:492:22)
    at async ObjectEditor.selectTarget (http://localhost:9011/lively.ide/js/objecteditor/index.js:682:30)
    at async ObjectEditor.browse (http://localhost:9011/lively.ide/js/objecteditor/index.js:861:17)
    at async Function.open (http://localhost:9011/lively.ide/js/objecteditor/index.js:2136:17)

**Comment by rickmcgeer** [comment]
Error Message is:
TypeError: __lvVarRecorder.defVar_local://lively-object-modules/MyClass/index.js is not a function

    at Object.execute (local://lively-object-modules/MyClass/index.js:10:89)
    at Window.moduleSourceChangeEsm (http://localhost:9011/lively.modules/src/change.js:78:21)
    at async Window.moduleSourceChange (http://localhost:9011/lively.modules/src/change.js:15:24)
    at async Promise.all (index 1)
    at async ObjectModule.createDefaultClassDeclaration (http://localhost:9011/lively.classes/object-classes.js:516:15)
    at async ObjectPackage.adoptObject (http://localhost:9011/lively.classes/object-classes.js:260:27)
    at async ObjectEditor_interactivelyAddObjectPackageAndMethod_.withContextDo.objPkgName.objPkgName (http://localhost:9011/lively.ide/js/objecteditor/index.js:1238:21)
    at async ObjectEditorContext.withContextDo (http://localhost:9011/lively.ide/js/objecteditor/context.js:296:24)
    at async ObjectEditor.withContextDo (http://localhost:9011/lively.ide/js/objecteditor/index.js:699:22)
    at async ObjectEditor.interactivelyAddObjectPackageAndMethod (http://localhost:9011/lively.ide/js/objecteditor/index.js:1236:19)

**Comment by rickmcgeer** [comment]
Tried with FastLoad on and got a different error message:
Error: Error evaluating local://lively-object-modules/MyClass/index.js:
SyntaxError: Unexpected token 'export'
    at eval (<anonymous>)
    at SystemJSLoader.__exec (http://localhost:9011/lively.modules/src/change.js:170:18)
    at Window.__evaluateGlobalLoadSource (http://localhost:9011/lively.modules/src/change.js:155:19)
    at executeGlobalModule (http://localhost:9011/lively.modules/src/change.js:131:23)
    at Window.runExecuteOfGlobalModule (http://localhost:9011/lively.modules/src/change.js:185:32)
    at Window.doInstantiateGlobalModule (http://localhost:9011/lively.modules/src/change.js:134:28)
    at Window.moduleSourceChangeGlobal (http://localhost:9011/lively.modules/src/change.js:94:33)
    at async Window.moduleSourceChange (http://localhost:9011/lively.modules/src/change.js:17:24)
    at async Promise.all (index 1)
    at async ObjectModule.createDefaultClassDeclaration (http://localhost:9011/lively.classes/object-classes.js:516:15)

    at SystemJSLoader.__exec (http://localhost:9011/lively.modules/src/change.js:174:15)
    at Window.__evaluateGlobalLoadSource (http://localhost:9011/lively.modules/src/change.js:155:19)
    at executeGlobalModule (http://localhost:9011/lively.modules/src/change.js:131:23)
    at Window.runExecuteOfGlobalModule (http://localhost:9011/lively.modules/src/change.js:185:32)
    at Window.doInstantiateGlobalModule (http://localhost:9011/lively.modules/src/change.js:134:28)
    at Window.moduleSourceChangeGlobal (http://localhost:9011/lively.modules/src/change.js:94:33)
    at async Window.moduleSourceChange (http://localhost:9011/lively.modules/src/change.js:17:24)
    at async Promise.all (index 1)
    at async ObjectModule.createDefaultClassDeclaration (http://localhost:9011/lively.classes/object-classes.js:516:15)
    at async ObjectPackage.adoptObject (http://localhost:9011/lively.classes/object-classes.js:260:27)

**Comment by merryman** [comment]
Should be fixed now in b47c0c7c52a1313677eccd8dd06e8f5840a0fe39
