### ISSUE TITLE
Can't load a world on galyleobeta.enagelively.com

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#243]
Hangs on "world loader".  Here is the trace from the console.  It appears to be the three.dew.js issue which we have seen before:
```
world.js:348 Uncaught (in promise) (SystemJS) Cannot read property 'push' of undefined
	TypeError: Cannot read property 'push' of undefined
	    at BoxGeometry.addGroup (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:7687:52)
	    at buildPlane (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:8527:23)
	    at BoxGeometry_initialize_ (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:8478:15)
	    at new BoxGeometry (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:8452:60)
	    at eval (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:32142:38)
	    at eval (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:9:61)
	    at dew (https://dev.jspm.io/npm:three@0.127.0/build/three.dew.js:10:6)
	    at execute (https://dev.jspm.io/three:10:26)
	Error loading local://lively-object-modules/WebGLCanvas/index.js
addToError @ system.src.js:123
linkSetFailed @ system.src.js:680
(anonymous) @ system.src.js:622
doDynamicExecute @ system.src.js:760
link @ system.src.js:957
doLink @ system.src.js:621
updateLinkSetOnLoad @ system.src.js:664
(anonymous) @ system.src.js:486
three.dew.js:7687 Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
    at BoxGeometry.addGroup (three.dew.js:7687)
    at buildPlane (three.dew.js:8527)
    at BoxGeometry_initialize_ (three.dew.js:8478)
    at new BoxGeometry (three.dew.js:8452)
    at eval (three.dew.js:32142)
    at eval (three.dew.js:9)
    at dew (three.dew.js:10)
    at execute (three:10)
    at ensureEvaluated (system.src.js:3360)
    at ensureEvaluated (system.src.js:3352)
```

**Comment by merryman** [comment]
Fixed in 8574809f. Please rebuild the container.
