### ISSUE TITLE
Can not start world

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#277]
```
2021-05-26T07:38:19.459Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
```

I used Node version 13

**Comment by frcroth** [comment]
Full log:
```
./start.sh
[lively.modules] SystemJS configured with lively.transpiler & babel
2021-05-26T07:36:23.346Z - info: [lively.server] system base directory: /home/felix/Documents/Uni/BP/lively.next
2021-05-26T07:36:23.353Z - error: (node:130846) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2021-05-26T07:36:24.468Z - info: [lively.server] 1. preparing system
2021-05-26T07:36:24.927Z - error: (node:130846) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
2021-05-26T07:36:25.747Z - info: [lively.server] 2. loading /home/felix/Documents/Uni/BP/lively.next/config.js
2021-05-26T07:36:25.751Z - info: [lively.server] 3. starting server
2021-05-26T07:36:25.789Z - error: cannot load jsdav: Error: Cannot find module '@pylonide/jsdav/lib/DAV/handler'
Require stack:
- /home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/dist/system.src.js
- /home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/index.js
- /home/felix/Documents/Uni/BP/lively.next/lively.server/index.js
- /home/felix/Documents/Uni/BP/lively.next/lively.server/bin/start-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._resolveFilename (/home/felix/Documents/Uni/BP/lively.next/flatn/module-resolver.js:20:36)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at SystemJSNodeLoader.require [as _nodeRequire] (internal/modules/cjs/helpers.js:72:18)
    at loadJsDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:47:178)
    at execute (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:55:8)
    at ensureEvaluated (/home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/dist/system.src.js:3363:26)
    at Object.execute (/home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/dist/system.src.js:3513:13)
    at doDynamicExecute (/home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/dist/system.src.js:766:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/dist/system.src.js',
    '/home/felix/Documents/Uni/BP/lively.next/lively.next-node_modules/systemjs/0.19.40/index.js',
    '/home/felix/Documents/Uni/BP/lively.next/lively.server/index.js',
    '/home/felix/Documents/Uni/BP/lively.next/lively.server/bin/start-server.js'
  ]
}
2021-05-26T07:36:26.121Z - error: Error in setup of plugin jsdav:
TypeError: Cannot read property 'new' of undefined
    at LivelyDAVPlugin.patchServerForJsDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:116:52)
    at LivelyDAVPlugin.setup (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:109:20)
    at LivelyServer.addPlugins (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:197:88)
2021-05-26T07:36:26.131Z - info: [lively.server] 4. server sucessfully started
2021-05-26T07:36:26.150Z - info: [l2l] L2LTracker(l2l, open: true) client connected /l2l#M6eKP5EFAU0JHJffAAAA 127.0.0.1
2021-05-26T07:36:26.165Z - info: Reconnected at 09:36:26 GMT+0200 (Central European Summer Time)
2021-05-26T07:36:26.175Z - info: headless-broker ready
2021-05-26T07:36:31.259Z - info: [l2l] L2LTracker(l2l, open: true) client connected /l2l#3-Tj0VE9ZdNHtJCqAAAB 127.0.0.1
2021-05-26T07:36:42.145Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
2021-05-26T07:36:42.153Z - error: Error in handleRequest of jsdav:
TypeError: __lvVarRecorder.DavHandler is not a constructor
    at LivelyDAVPlugin.callDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:160:31)
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:154:20)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
2021-05-26T07:36:42.154Z - error: Error in handleRequest of jsdav:
TypeError: __lvVarRecorder.DavHandler is not a constructor
    at LivelyDAVPlugin.callDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:160:31)
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:154:20)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
2021-05-26T07:36:42.995Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
2021-05-26T07:36:48.297Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
2021-05-26T07:36:48.307Z - error: Error in handleRequest of jsdav:
TypeError: __lvVarRecorder.DavHandler is not a constructor
    at LivelyDAVPlugin.callDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:160:31)
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:154:20)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
2021-05-26T07:36:48.308Z - error: Error in handleRequest of jsdav:
TypeError: __lvVarRecorder.DavHandler is not a constructor
    at LivelyDAVPlugin.callDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:160:31)
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:154:20)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
2021-05-26T07:36:49.044Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
2021-05-26T07:38:19.399Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
2021-05-26T07:38:19.413Z - error: Error in handleRequest of jsdav:
TypeError: __lvVarRecorder.DavHandler is not a constructor
    at LivelyDAVPlugin.callDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:160:31)
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:154:20)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
2021-05-26T07:38:19.416Z - error: Error in handleRequest of jsdav:
TypeError: __lvVarRecorder.DavHandler is not a constructor
    at LivelyDAVPlugin.callDAV (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:160:31)
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:154:20)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
2021-05-26T07:38:19.459Z - error: Error in handleRequest of jsdav:
TypeError: Cannot read property '/lively.freezer/loading-screen/load.js' of undefined
    at LivelyDAVPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/dav.js:143:60)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at FileUploadPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/file-upload.js:119:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at ObjectDBPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/objectdb.js:85:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at SocketioPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/socketio.js:92:17)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
    at EvalPlugin.handleRequest (file:///home/felix/Documents/Uni/BP/lively.next/lively.server/plugins/eval.js:53:24)
    at file:///home/felix/Documents/Uni/BP/lively.next/lively.server/server.js:147:26
```

**Comment by merryman** [comment]
You forgot to run `./install.sh` after a pull.

**Comment by frcroth** [comment]
I did run ./install.sh

**Comment by merryman** [comment]
Just checked, there was a missing dependency. Can you pull and install again?

**Comment by frcroth** [comment]
Yes now I can open the world
