### ISSUE TITLE
Component not getting found

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#327]
When I try to instantiate the component "danStartScreen" in the world DAN3, I get the following error message:
`Master component "danStartScreen" can not be found in "DAN3"
Error: Master component "danStartScreen" can not be found in "DAN3"
    at StyleGuideResource_read_ (https://matt.engagelively.com/lively.morphic/style-guide.js:1103:23)
    at async PartResource_read_ (https://matt.engagelively.com/lively.morphic/partsbin.js:633:39)
    at async Morph.eval (local://lively-object-modules/DAN3/dANNarrow.js_doit_1632109452186:6:69)`

It clearly shows in the component browser:
![image](https://user-images.githubusercontent.com/656259/133955273-2fce0cae-1da7-4930-be17-5c05084c36d2.png)

Now, I had earlier misspelled the name on the component itself as "danStartSceen" but even after correction I am still seeing this.
I'm going to rebuild a new component with a different name but leave this open for debugging.
World is https://matt.engagelively.com/worlds/load?name=DAN3

**Comment by merryman** [comment]
I think this may have been a problem with the internal cache that was not invalidated once you renamed the component. Let's see. I am working on a new way to organize the components in files instead of storing them away in worlds. My hope is that it will make situations like these disappear.
