### ISSUE TITLE
Browser Crashes Upon Opening New Tab

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#362]
Opening a new browser tab when a markdown file is currently being edited in the browser crashes with the following error:

```
Uncaught (in promise) TypeError: this.editorPlugin.runEval is not a function
    at BrowserModel_toggleWindowStyle_ (:9011/lively.ide/js/browser/index.js:1151:44)
    at BrowserModel_browse_ (:9011/lively.ide/js/browser/index.js:1250:26)
    at async BrowserModel_browsedTabChanged_ (:9011/lively.ide/js/browser/index.js:2267:15)
```

**Comment by linusha** [comment]
Fixed in b6ee908296f8176ece04e435dcd50e5e55e882d8.
