### ISSUE TITLE
Errors when grabbing morph and trying to drop it

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#432]
https://user-images.githubusercontent.com/6863832/180442778-2cf25b29-c39d-4157-8d1c-fdb7ef4a4421.mp4

Error:
```
Error: Error in event handler <GrabHaloItem - grab>.onDragEnd: TypeError: Cannot read properties of null (reading 'addTarget')
    at GrabHaloItem.GrabHaloItem_stop_ (http://localhost:9011/lively.halos/morph.js:1166:20)
    at GrabHaloItem.GrabHaloItem_onDragEnd_ (http://localhost:9011/lively.halos/morph.js:1199:20)
    at EventDispatcher.EventDispatcher_dispatchEvent_ (http://localhost:9011/lively.morphic/events/EventDispatcher.js:734:46)
    at eval (http://localhost:9011/lively.morphic/events/EventDispatcher.js:792:42)
    at Array.forEach (<anonymous>)
    at EventDispatcher.EventDispatcher_dispatchDOMEvent_ (http://localhost:9011/lively.morphic/events/EventDispatcher.js:792:22)
    at fn (http://localhost:9011/lively.morphic/events/EventDispatcher.js:446:40)

    at EventDispatcher.EventDispatcher_dispatchEvent_ (http://localhost:9011/lively.morphic/events/EventDispatcher.js:736:25)
    at eval (http://localhost:9011/lively.morphic/events/EventDispatcher.js:792:42)
    at Array.forEach (<anonymous>)
    at EventDispatcher.EventDispatcher_dispatchDOMEvent_ (http://localhost:9011/lively.morphic/events/EventDispatcher.js:792:22)
    at fn (http://localhost:9011/lively.morphic/events/EventDispatcher.js:446:40)
```

**Comment by linusha** [comment]
Thanks for reporting this!
Are you dropping in some special kind of target? Or are you just grabbing and dropping the morph to a different position in the world?

**Comment by frcroth** [comment]
Just in the world

**Comment by linusha** [comment]
After watching the video some more, I think what happened here is that somehow the system tried dropping the morph inside of the Halo's tooltip at first, which messes up some state.
I could not even grab a morph with a second tooltip still being visible on the current `main`. I'll close this for now and reopen if the problem should arise anew.
