### ISSUE TITLE
part is not a function...

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#509]
Error message is:
```
TypeError: __lvVarRecorder.part is not a function

    at Text.eval (http://127.0.0.1:9011/galyleo-dashboard/studio/ui.cp.js_doit_1665096229699:6:66)
    at eval (http://127.0.0.1:9011/galyleo-dashboard/studio/ui.cp.js_doit_1665096229699:11:4)
    at Text._eval (eval at evalJS (http://127.0.0.1:9011/lively.lang/function.js), <anonymous>:2:10)
    at Window.runEval [as vmRunEval] (http://127.0.0.1:9011/lively.vm/lib/eval.js:113:45)
    at ModuleRecord.runEval (http://127.0.0.1:9011/lively.vm/lib/esm-eval.js:176:34)
    at ModuleRecord.runEval (http://127.0.0.1:9011/lively.vm/index.js:29:50)
    at LocalCoreInterface.LocalCoreInterface_runEval_ (http://127.0.0.1:9011/lively-system-interface/interfaces/local-system.js:91:41)
    at Interface.Interface_runEval_ (http://127.0.0.1:9011/lively-system-interface/index.js:132:41)
    at JavaScriptEditorPlugin.JavaScriptEditorPlugin_runEval_ (http://127.0.0.1:9011/lively.ide/js/editor-plugin.js:365:31)
    at Text.Text_doEval_ (http://127.0.0.1:9011/lively.morphic/text/morph.js:3115:29)
```

Attempting `part(GalyleoDashboardStudio).openInWorld()`

$world.execCommand("open browser", {moduleName: "studio/ui.cp.js", packageName: "galyleo-dashboard", codeEntity: "GalyleoDashboardStudio"});

**Comment by linusha** [comment]
Are you sure that you have imported `part`? You can check with right-click -> fix undefined variables.

**Comment by rickmcgeer** [comment]
Yes, I am
`import { component, ViewModel, part } from 'lively.morphic/components/core.js';`

**Comment by merryman** [comment]
Was due to an error in another dependency that prevented the module form loading, so nothing got initialized.
