### ISSUE TITLE
Better error messages when browser fails loading a module

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#681]
When I open a new browser for the first time in a project, and click on 'Load Existing Project' and click 'gravity-game' from the module list, I get the following error:
```
Error in interactive command add package: Error: (SystemJS) Cannot read properties of undefined (reading 'replace')
	TypeError: Cannot read properties of undefined (reading 'replace')
	    at eval (http://127.0.0.1:9011/lively.lang/string.js:315:131)
	    at Array.reduce (<anonymous>)
	    at ModuleRecord.joinPath (http://127.0.0.1:9011/lively.lang/string.js:315:80)
	    at Window.getPropSettings (http://127.0.0.1:9011/lively.morphic/helpers.js:70:40)
	    at Window.getStylePropertiesFor (http://127.0.0.1:9011/lively.morphic/helpers.js:76:54)
	    at eval (http://127.0.0.1:9011/lively.morphic/components/policy.js:351:40)
	    at ModuleRecord.mapTree (http://127.0.0.1:9011/lively.lang/tree.js:40:12)
	    at PolicyApplicator.StylePolicy_ensureStylePoliciesInSpec_ (http://127.0.0.1:9011/lively.morphic/components/policy.js:339:55)
	    at PolicyApplicator.StylePolicy_initialize_ (http://127.0.0.1:9011/lively.morphic/components/policy.js:137:32)
	    at new PolicyApplicator (http://127.0.0.1:9011/lively.morphic/components/policy.js:707:67)
	Error loading http://127.0.0.1:9011/gravity-game/index.js
(SystemJS) Cannot read properties of undefined (reading 'replace')
	TypeError: Cannot read properties of undefined (reading 'replace')
	    at eval (http://127.0.0.1:9011/lively.lang/string.js:315:131)
	    at Array.reduce (<anonymous>)
	    at ModuleRecord.joinPath (http://127.0.0.1:9011/lively.lang/string.js:315:80)
	    at Window.getPropSettings (http://127.0.0.1:9011/lively.morphic/helpers.js:70:40)
	    at Window.getStylePropertiesFor (http://127.0.0.1:9011/lively.morphic/helpers.js:76:54)
	    at eval (http://127.0.0.1:9011/lively.morphic/components/policy.js:351:40)
	    at ModuleRecord.mapTree (http://127.0.0.1:9011/lively.lang/tree.js:40:12)
	    at PolicyApplicator.StylePolicy_ensureStylePoliciesInSpec_ (http://127.0.0.1:9011/lively.morphic/components/policy.js:339:55)
	    at PolicyApplicator.StylePolicy_initialize_ (http://127.0.0.1:9011/lively.morphic/components/policy.js:137:32)
	    at new PolicyApplicator (http://127.0.0.1:9011/lively.morphic/components/policy.js:707:67)
	Error loading http://127.0.0.1:9011/gravity-game/index.js
```
This then happens with all existing package loads.
However, when I load galyleo-dashboard into a browser first, gravity-game subsequently loads with no problem.

**Comment by linusha** [comment]
When I load the gravitygame package, I get the following error:

```
Error in interactive command add package: Error: (SystemJS) Cannot read http://localhost:9011/galyleo-dashboard/studio/inputs/toggle.cp.js: Not Found 404
	Error: Cannot read http://localhost:9011/galyleo-dashboard/studio/inputs/toggle.cp.js: Not Found 404
	    at WebDAVResource.WebDAVResource_read_ (http://localhost:9011/lively.resources/src/http-resource.js:591:23)
	    at async SystemJSLoader.fetchResource (http://localhost:9011/lively.modules/src/resource.js:35:33)
	Error loading http://localhost:9011/galyleo-dashboard/studio/inputs/toggle.cp.js as "../galyleo-dashboard/studio/inputs/toggle.cp.js" from http://localhost:9011/gravity-game/index.js
```

This absolutely makes sense, since you are importing stuff from the galyleodashboard package, you need to load that one beforehand.

With the new project architecture, I think we will also think about how to make dependencies in custom packages like this easier to handle, but for now, I think this is working as intended. @merryman feel free to chime in if you disagree, please!

**Comment by rickmcgeer** [comment]
Thanks, @linusha, this makes perfect sense (and is a big relief!)  One takeaway here is I could have figured this out easily with a more explanatory browser error message.  Maybe a separate ticket?  Right now, when the browser refuses to load a module, the programmer is kind of stuck.

**Comment by linusha** [comment]
No need to make a separate ticket, we will think about this and come back to edit this one.
Glad its working for now.
