### ISSUE TITLE
Clicking on the "New Browser Tab" cross in the browser hangs it

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#682]
And after that, attempting to open any new browser fails and gives this error message:
```
Error in interactive command open browser: TypeError: files.map is not a function
TypeError: files.map is not a function
    at PackageTreeData.PackageTreeData_listEditableFilesInDir_ (http://127.0.0.1:9011/lively.ide/js/browser/index.js:743:28)
    at async PackageTreeData.PackageTreeData_listEditableFilesInPackage_ (http://127.0.0.1:9011/lively.ide/js/browser/index.js:713:22)
    at async PackageTreeData.PackageTreeData_collapse_ (http://127.0.0.1:9011/lively.ide/js/browser/index.js:768:35)
    at async PackageTreeData.TreeData_uncollapseAll_ (http://127.0.0.1:9011/lively.components/tree.js:962:37)
    at async PackageTreeData.TreeData_uncollapseAll_ (http://127.0.0.1:9011/lively.components/tree.js:965:19)
    at async MullerColumnViewModel.MullerColumnViewModel_setExpandedPath_ (http://127.0.0.1:9011/lively.components/muller-columns.cp.js:181:15)
    at async BrowserModel.BrowserModel_selectModuleNamed_ (http://127.0.0.1:9011/lively.ide/js/browser/index.js:1492:19)
    at async BrowserModel.BrowserModel_browse_ (http://127.0.0.1:9011/lively.ide/js/browser/index.js:1335:19)
    at async Object.exec (http://127.0.0.1:9011/lively.ide/world-commands.js:1152:25)
```

**Comment by rickmcgeer** [comment]
I also noticed that the server had crashed, which may have happened before or after the incident -- IOW, may be an effect, a cause, or neither.

**Comment by merryman** [comment]
If the server crashed it is indeed impossible for the browser to open another tab, since its not able to fetch the source information. I am inclined to close this ticket if you do not encounter this bug on a regular basis.
