### ISSUE TITLE
Ghost morphs left after removal

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#764]
**Describe the bug**
This may be related to #756.  I'm building a world (not Galyleo, so no re-use of the LivelyUI), and I have a Morph that I want to remove when clicked on and replaced with another Morph, so the code is:
```
onMouseDown(evt) {
    this.remove();
   new StorePageOne().openInWorld();
}
```
See the attached screenshot:

1. the morph `vault` is removed, but a Halo around it remains (and I hadn't selected the Halo)
2. The morph appears in the Scene Graph tab
3. the new morph isn't in the Scene Graph tab
4. Clicking on the trash can icon on the Halo produces this error
```
Error: Error in event handler <CloseHaloItem - close>.onMouseDown: TypeError: Cannot read properties of null (reading 'undoStart')
    at CloseHaloItem.CloseHaloItem_update_ (http://127.0.0.1:9011/lively.halos/morph.js:1026:17)
    at CloseHaloItem.CloseHaloItem_onMouseDown_ (http://127.0.0.1:9011/lively.halos/morph.js:1042:20)
    at EventDispatcher.EventDispatcher_dispatchEvent_ (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:728:46)
    at eval (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:786:42)
    at Array.forEach (<anonymous>)
    at EventDispatcher.EventDispatcher_dispatchDOMEvent_ (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:786:22)
    at fn (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:440:40)

    at EventDispatcher.EventDispatcher_dispatchEvent_ (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:730:25)
    at eval (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:786:42)
    at Array.forEach (<anonymous>)
    at EventDispatcher.EventDispatcher_dispatchDOMEvent_ (http://127.0.0.1:9011/lively.morphic/events/EventDispatcher.js:786:22)
```

**To Reproduce**
I've created a github repo [engageLively/mc](https://github.com/engageLively/mcfarlane) and invited @linusha as a reader.  @merryman should already have access.  Run `new Vault().openInWorld()` and then right click on the vault.

**Screenshots**
![Screenshot 2023-03-14 212517](https://user-images.githubusercontent.com/656259/225208636-d0be7483-58b3-4c0b-81ff-58e9b6651570.png)

**Setup**
Please delete non-applicable items!

- Windows
- Linux
- Docker

**Version**: Please paste the lively.next commit on which the problem occurred here (short version from the Version Checker in the bottom left corner is sufficient).
From git log (short version still unavailable)
commit 0e22dbdb9416630eaf14c02b4da607af029b508d

**Comment by linusha** [comment]
@rickmcgeer are you in hand or in halo mode when you do this?

It's curious, for me it works seamless (in Hand mode), and in Halo mode I do not trigger the `onMouseDown` at all, so everything works as expected :open_mouth:.

https://user-images.githubusercontent.com/14252419/225283902-3ef17add-23a0-46fe-99e2-6e787a1f0ee6.mp4

**Comment by linusha** [comment]
@rickmcgeer By the way, I think if you update your lively the Version Checker should work :slightly_smiling_face:
