### ISSUE TITLE
Weird behavior when I attempted to grab a morph and drop it elsewhere

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#85]
Grabbed a button to move it out of a Rectangle.  Got an orange box with the shape of the rectangle moving on the screen, and a ton of alert boxes with this message:
ypeError: Cannot read property 'onHaloGrabover' of undefined

    at Halo.toggleMorphHighlighter (/lively.halos/morph.js:688)
    at GrabHaloItem.valueForPropertyDisplay (/lively.halos/morph.js:1596)
    at Halo.updatePropertyDisplay (/lively.halos/morph.js:585)
    at Halo.alignWithTarget (/lively.halos/morph.js:374)
    at GrabHaloItem.update (/lively.halos/morph.js:1641)
    at callOrSetTarget (/lively.bindings/index.js:500)
    at AttributeConnection.update (/lively.bindings/index.js:507)
    at Hand.connectionWrapper [as update] (/lively.bindings/index.js:595)
    at LivelyWorld.onMouseMove (/lively.morphic/world.js:272)
    at LivelyWorld.onMouseMove (/lively.ide/world.js:254)
setStatusMessage @ /lively.ide/world.js:952
/lively.ide/world.js:952 Error: Error in event handler <GrabHaloItem - grab>.onDragEnd: TypeError: Cannot read property 'id' of undefined
    at Function.interceptDrop (https://matt.engagelively.com/lively.halos/morph.js:3077:37)
    at GrabHaloItem.stop (https://matt.engagelively.com/lively.halos/morph.js:1627:48)
    at GrabHaloItem.onDragEnd (https://matt.engagelively.com/lively.halos/morph.js:1653:20)
    at EventDispatcher.dispatchEvent (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:678:46)
    at eval (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:734:42)
    at Array.forEach (<anonymous>)
    at EventDispatcher.dispatchDOMEvent (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:734:22)
    at fn (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:430:38)

    at EventDispatcher.dispatchEvent (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:680:25)
    at eval (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:734:42)
    at Array.forEach (<anonymous>)
    at EventDispatcher.dispatchDOMEvent (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:734:22)
    at fn (https://matt.engagelively.com/lively.morphic/events/EventDispatcher.js:430:38)

Screenshot:
![Screen Shot 2020-11-12 at 06 43 16](https://user-images.githubusercontent.com/656259/98954732-f2ba3400-24b2-11eb-8850-078bb8e14051.png)

**Comment by merryman** [comment]
Hard to reproduce, but I will add some more checks to that line of code.

**Comment by merryman** [comment]
@rickmcgeer Have you run into this issue again recently? If so, lets gather more details. If not I will close this.

**Comment by linusha** [comment]
Seems not to be reproducible at the moment.
