### ISSUE TITLE
Can't remove a class from a morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#88]
Clicked on the - sign in the left-hand sidebar and it failed.  Error message is:
Error in interactive command remove method or class: TypeError: Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at eval (https://matt.engagelively.com/lively.ide/js/objecteditor/index.js:1312:52)
    at ObjectEditorContext.withContextDo (https://matt.engagelively.com/lively.ide/js/objecteditor/context.js:296:30)
    at ObjectEditor.withContextDo (https://matt.engagelively.com/lively.ide/js/objecteditor/index.js:716:41)
    at ObjectEditor.interactivelyRemoveMethodOrClass (https://matt.engagelively.com/lively.ide/js/objecteditor/index.js:1311:64)
    at Object.exec (https://matt.engagelively.com/lively.ide/js/objecteditor/index.js:1958:30)
    at CommandHandler.exec (https://matt.engagelively.com/lively.morphic/CommandHandler.js:126:36)
    at ObjectEditor.execCommand (https://matt.engagelively.com/lively.morphic/morph.js:2397:42)
    at callOrSetTarget (https://matt.engagelively.com/lively.bindings/index.js:500:82)
    at AttributeConnection.update (https://matt.engagelively.com/lively.bindings/index.js:507:92)
    at Window.signal (https://matt.engagelively.com/lively.bindings/index.js:78:11)

**Comment by merryman** [comment]
Thanks, fixed in 3b613e32283b622f0b9e1a9cc86510a878784624
