### ISSUE TITLE
Setting rotation in configuration blows up the renderer

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#886]
**Describe the bug**
I attempted to create a Morph with the rotation set in the configuration, namely:
```
let jump = new JumpPortal({
  name: 'caravan',
      position: pt(469, 186),
      extent: pt(279, 97),
      rotation: '-0.46282599168932226',
      url: 'https://www.360cities.net/image/dromedaries-in-the-desert'
})
```
`JumpPortal` is a trivial subclass of `Morph`.

And got a render failure similar to the failure I mentioned last night, with the following error message:
```
renderer.js:239 Error rendering morphs: TypeError: rotation.toFixed is not a function
    at Window.addTransform (property-dom-mapping.js:83:45)
    at Window.styleProps (property-dom-mapping.js:44:21)
    at Window.defaultStyle (morphic-default.js:53:38)
    at Window.applyStylingToNode (morphic-default.js:26:38)
    at Renderer.Renderer_renderStylingChanges_ (renderer.js:561:31)
    at Renderer.Renderer_renderStep_ (renderer.js:285:22)
    at eval (renderer.js:237:24)
```

**To Reproduce**
Steps to reproduce the behavior. Please make sure to let us know if your problem requires the loading of custom components,...

**Screenshots**

**Setup**
Please delete non-applicable items!

- Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
a2f54f678bc0e2664d1d9589c4051010fdd87e53

**Comment by linusha** [comment]
That code cannot work, as rotation requires a number, and the above configuration contains a string. The same thing as a number works just fine:

https://github.com/LivelyKernel/lively.next/assets/14252419/d0c15fad-7554-4199-a79f-f0a4e61b7038

Is the concrete configuration something you wrote, or is that code that got created via the reconciliation or something?
In the first case I'll close here, in the latter one that is indeed a bug.

**Comment by linusha** [comment]
By the way, we merged #884 yesterday, which should prevent such cases from accidentally happening.

**Comment by rickmcgeer** [comment]
Ah, dumb copy and paste, my error
