### ISSUE TITLE
open javascript workspace fails and leads to popup buge

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#972]
**Describe the bug**

When I click on "Open Javascript Workspace..."  in the World Menu, nothing happens, and this appears in the console
```
Error in interactive command open javascript workspace: TypeError: Cannot read properties of null (reading 'width')
TypeError: Cannot read properties of null (reading 'width')
    at LivelyWorld.LivelyWorld_visibleBoundsExcludingStudioInterface_ (http://127.0.0.1:9011/lively.ide/world.js:252:67)
    at Function.Window_maximumBounds_ (http://127.0.0.1:9011/lively.components/window.js:1050:29)
    at Workspace.Window_updateNonMinimizedBounds_ (http://127.0.0.1:9011/lively.components/window.js:76:73)
    at Workspace.set [as position] (http://127.0.0.1:9011/lively.components/window.js:941:26)
    at Workspace.Morph_moveBy_ (http://127.0.0.1:9011/lively.morphic/morph.js:924:29)
    at Workspace.Morph_align_ (http://127.0.0.1:9011/lively.morphic/morph.js:918:27)
    at Workspace.set [as center] (http://127.0.0.1:9011/lively.morphic/morph.js:2838:33)
    at Window.prepareInstanceForProperties (http://127.0.0.1:9011/lively.classes/properties.js:195:23)
    at Workspace.value (http://127.0.0.1:9011/lively.classes/properties.js:88:25)
    at Workspace.Morph_initialize_ (http://127.0.0.1:9011/lively.morphic/morph.js:186:20)
```

**To Reproduce**
Steps to reproduce the behavior. Please make sure to let us know if your problem requires the loading of custom components,...

**Screenshots**

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
34f27b39a9805265b86369a67ee0ffe665dc1f8e

**Comment by rickmcgeer** [comment]
The problem disappeared when I opened the project in a new window, so I suspect it had to do with resizing the browser after I opened the project

**Comment by linusha** [comment]
I cannot reproduce this. I am not sure how, but it might be that the constantly failing font measuring trips this up as well.

Could you try reproducing this once we have the font problem sorted out?

**Comment by linusha** [comment]
I assume this was related to a missing rebuild after we changed the font inclusion mechanism. @rickmcgeer please reopen if the problem persists.
